mysql:
    image: mysql:8.0
    container_name: local_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER=admin
      - MYSQL_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
