mysql:
    image: mysql:8.0
    container_name: local_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - "./.env"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_USER=admin
