# Sample of a decK config file
# Rename this file to kong.yaml
# Use deck validate to validate kong.yaml
# Use deck dump to export kong.yaml
# Use deck sync to import kong.yaml
# Use deck reset to delete all kong configuration

{
  "_format_version": "1.1",
  "services": [
    {
      "connect_timeout": 60000,
      "enabled": true,
      "host": "${{ env `DECK_HOST` }}",
      "name": "route",
      "path": "/api/${{ env `DECK_ROUTE` }}",
      "port": ${{ env `DECK_CONNECT_PORT` }},
      "protocol": "${{ env `DECK_PROTOCOL` }}",
      "read_timeout": 60000,
      "retries": 5,
      "routes": [
        {
          "https_redirect_status_code": 426,
          "methods": [
            "GET",
            "POST",
            "PUT",
            "DELETE"
          ],
          "name": "route",
          "path_handling": "v1",
          "paths": [
            "/${{ env `DECK_ROUTE` }}"
          ],
          "preserve_host": false,
          "protocols": [
            "http",
            "https"
          ],
          "regex_priority": 0,
          "request_buffering": true,
          "response_buffering": true,
          "strip_path": true
        }
      ],
      "write_timeout": 60000
    }
  ]
}