version: "3.9"
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: unless-stopped
    environment:
      LDAP_DOMAIN: example.ldap
      LDAP_ORGANISATION: example
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      # LDAP_BASE_DN: ""
    ports:
    - "389:389"
    volumes:
      - ./data:/var/lib/ldap
      - ./config:/etc/ldap/slapd.d
volumes:
  openldap: