version: "3.9"
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: unless-stopped
    environment:
      - LDAP_DOMAIN=sec4you.ldap
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD
      - LDAP_ORGANISATION=sec4you
    ports:
    - "389:389"
    volumes:
      - openldap:/var/lib/openldap
volumes:
  openldap: