version: "3.9"
services:
  strapi-server:
    image: strapi/strapi:latest
    container_name: strapi-server
    restart: unless-stopped
    depends_on:
      - strapi-database
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi-database
      DATABASE_NAME: strapi
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/srv/app
    networks:
      strapi:
        aliases:
          - strapi-server

  strapi-database:
    image: postgres:latest
    container_name: strapi-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - ./data:/var/lib/postgresql
    networks:
      strapi:
        aliases:
          - strapi-database

volumes:
  strapi-server:
  strapi-database:

networks:
  strapi: