version: "3.9"
services:
  mailcatcher:
    image: schickling/mailcatcher:latest
    container_name: mailcatcher
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "25:1025"
    volumes:
      - ./data:/var/lib/mailcatcher
volumes:
  mailcatcher: