version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=admin
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: