version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin" ]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"
    volumes: 
      - ./data:/var/lib/postgresql